const { Router } = require("express");
const express = require("express");
const router = express.Router();
const mapController = require("../controllers/mapController.js");
router.post("/insert", mapController.mapInsert);
router.post("/search", mapController.mapSearch);
router.post("/create", mapController.mapCreate);
router.get("/getAllMarker", mapController.mapGetAllMarker);
router.get("/showRTree", mapController.showRTree);
module.exports = router;
